{% set name = "gdk-pixbuf" %}
{% set version = "2.38.2" %}
{% set sha256 = "73fa651ec0d89d73dd3070b129ce2203a66171dfc0bd2caa3570a9c93d2d0781" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    sha256: {{ sha256 }}
    url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
    patches:
      - 0001-changed-perl-script-to-use-env.patch
      - no-shared-mime-info.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=gdk-pixbuf
    - {{ pin_subpackage('gdk-pixbuf', max_pin='x') }}

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - make
  host:
    - gettext  # [osx]
    - glib
    - gobject-introspection
    - make
    - jpeg
    - libtiff
    - libpng
    - zlib
  run:
    - gettext  # [osx]
    - glib
    - gobject-introspection
    - jpeg
    - libtiff
    - libpng
    - zlib

test:
  commands:
    - gdk-pixbuf-csource --version
    - gdk-pixbuf-query-loaders --help
    - gdk-pixbuf-pixdata --help

about:
  home: https://developer.gnome.org/gdk-pixbuf/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: "GdkPixbuf is a library for image loading and manipulation."

extra:
  recipe-maintainers:
    - notestaff
    - pkgw
