# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PERL=5.20.3.1  CONDA_PY=27
    - CONDA_PERL=5.22.0.1  CONDA_PY=27
    - CONDA_PERL=5.22.2.1  CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ib63ddkhVe3kN60suefPeLZlaXW7j4EH2ZD6eDI3WIf5X6ukbjf9AAO6QxIRapmjCVhkbR71JglPWkGoYfcY3O9mZJa7CzeTtRWPyglmsB5ta1cU+X9Aq89oJldmwWx+jptmRBt3mUn99DLJE+/h3RJNjITYahmSRW7xoG1ZY5BqAGpQpx6I1iS7JUYLGPVfCHfo0yj4EVRIIGilKrFOr/qEz2dnRyNwm9aJ1XqGEHwy/ks7RQGW5UoIjAMUcLmvO9wxTQlHWH/ci0kwfzQnvG85u1eDKqW3qY2dbcItZzKV7V9pKfgEQcWcWPfPSOZ/3NIfy8TAyzPCSYaiJVT23AvF4PWeAFJUGUB0mczbC1PbyBw7OAhR/YElr4KH1zQ1NHiAwb8p1xi+5JYlz3attr5moavSpkvio2Td+Y1Rx0oOmYoyigld3xDwN5GSGrlgV4isRuTW+WOw9WEHZE1+dtqcwTSFyzaBiv5M3k0cxGrHceb95JnZIBAKKQyxBhphbvhWt2QKpDinifa5uCaQ+u8thsAlA8g/W0yHHDnYpJwK7+v7bbmCpdB5Gdh+AFm8vqUxMXE1StYOgnu1uCVvRjLLKyr8Fd5O1Q1LigkdRhhl/JY3m7UkUaZqBV2FClXcywxY3cENCTeMRJu1K1WEXTzXW4VPYhxLe98ysUcWN0Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
