travis:
  secure:
    BINSTAR_TOKEN: ib63ddkhVe3kN60suefPeLZlaXW7j4EH2ZD6eDI3WIf5X6ukbjf9AAO6QxIRapmjCVhkbR71JglPWkGoYfcY3O9mZJa7CzeTtRWPyglmsB5ta1cU+X9Aq89oJldmwWx+jptmRBt3mUn99DLJE+/h3RJNjITYahmSRW7xoG1ZY5BqAGpQpx6I1iS7JUYLGPVfCHfo0yj4EVRIIGilKrFOr/qEz2dnRyNwm9aJ1XqGEHwy/ks7RQGW5UoIjAMUcLmvO9wxTQlHWH/ci0kwfzQnvG85u1eDKqW3qY2dbcItZzKV7V9pKfgEQcWcWPfPSOZ/3NIfy8TAyzPCSYaiJVT23AvF4PWeAFJUGUB0mczbC1PbyBw7OAhR/YElr4KH1zQ1NHiAwb8p1xi+5JYlz3attr5moavSpkvio2Td+Y1Rx0oOmYoyigld3xDwN5GSGrlgV4isRuTW+WOw9WEHZE1+dtqcwTSFyzaBiv5M3k0cxGrHceb95JnZIBAKKQyxBhphbvhWt2QKpDinifa5uCaQ+u8thsAlA8g/W0yHHDnYpJwK7+v7bbmCpdB5Gdh+AFm8vqUxMXE1StYOgnu1uCVvRjLLKyr8Fd5O1Q1LigkdRhhl/JY3m7UkUaZqBV2FClXcywxY3cENCTeMRJu1K1WEXTzXW4VPYhxLe98ysUcWN0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
